# Generated by Django 4.1.7 on 2023-03-14 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvTable2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('link', models.CharField(blank=True, max_length=6553, null=True)),
            ],
            options={
                'db_table': 'csv_table_2',
                'managed': False,
            },
        ),
    ]
